- name: Clone repo
  git:
    repo: "{{ libxdc_url }}"
    dest: "{{ libxdc_root }}"
    version: "{{ libxdc_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"

- name: Build libxdc
  make:
    chdir: "{{ libxdc_root }}"
    params:
      --jobs: "{{ ansible_processor_nproc }}"
  environment:
    C_INCLUDE_PATH: "{{ capstone_root }}/include:{{ libxdc_root }}"
    LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"
    LD_LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"
