- hosts: all
  vars_files:
    - vars.yml
  environment:
    PIPENV_VENV_IN_PROJECT: 1
    # ignore current ansible venv and force Pipenv to create it's own
    PIPENV_IGNORE_VIRTUALENVS: 1

  roles:
    - role: kafl
      tags:
        - kafl
