- name: Install required packages
  ansible.builtin.apt:
    # required for lddtree
    name: 
      - pax-utils
      - qemu
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - virtinst
      - bridge-utils
    state: present
  become: true
  tags:
    - virtualization_packages

- name: Enable and start libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started
  tags:
    - libvirtd_service

- name: Clone required submodules
  ansible.builtin.command: >-
    "git submodule update --init --depth 200
    --jobs {{ ansible_processor_nproc }}
    {{ dvkm_sub_path }}
    {{ linux_agent_sub_path }}"
    # noqa: command-instead-of-module
  args:
    chdir: "{{ examples_root }}"
