- hosts: all
  environment:
    http_proxy: "{{ proxy_env.http_proxy | default(omit) }}"
    https_proxy: "{{ proxy_env.https_proxy | default(omit) }}"

  roles:
    - role: intellabs.kafl.fuzzer
      tags:
        - fuzzer
