- hosts: all
  vars_files:
    - vars.yml
  environment:
    PIPENV_VENV_IN_PROJECT: 1
    # ignore current ansible venv and force Pipenv to create it's own
    PIPENV_IGNORE_VIRTUALENVS: 1
  pre_tasks:
    - name: Checking for intel_pt support in cpuinfo
      shell: grep intel_pt /proc/cpuinfo
      register: res
      failed_when: res.rc != 0

    - name: Ensure minimal deps are available
      package:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - sudo
        - dpkg

  roles:
    - kafl
    - capstone
    - libxdc
    - qemu
    - radamsa

  post_tasks:
    - name: Ensure current user is in kvm group
      user:
        name: "{{ ansible_user_id }}"
        groups: kvm
        append: yes
