- name: Install kAFL kernel and configure boot entry
  block:
    - name: Install dependencies
      package:
        name:
          - linux-base
          - kmod
      become: yes

    - name: Create tempory directory for downloaded packages
      tempfile:
        state: directory
      register: down_dir

    - name: Download deb packages
      get_url:
        url: "{{ item }}"
        dest: "{{ down_dir.path }}"
      with_items: "{{ kernel_deb_urls }}"

    - name: Install kAFL kernel
      shell: dpkg -i "{{ down_dir.path }}"/*.deb
      become: yes

    - name: Configure boot entry to select new kernel
      lineinfile:
        regexp: ^GRUB_DEFAULT=
        line: GRUB_DEFAULT="{{ kernel_grub_default }}"
        dest: /etc/default/grub
      become: yes
      tags:
        - update_grub

    - name: Update GRUB
      command: update-grub
      become: yes
      tags:
        - update_grub

    - name: Remove temporary download directory
      file:
        path: "{{ down_dir.path }}"
        state: absent

    - name: Reboot on new kernel
      reboot:
      become: yes
      when: ansible_connection != 'local'
      tags:
        - reboot_kernel
  when: not kernel_search_uname in ansible_kernel
