- block:
  - name: Install required dependencies
    package:
      name:
        - build-essential
    become: yes

  - name: Create temporary directory
    tempfile:
      state: directory
    register: temp_compile

  - name: Upload support_test.c
    copy:
      src: files/support_test.c
      dest: "{{ temp_compile.path }}/support_test.c"

  - name: Compile support_test.c
    command: gcc "{{ temp_compile.path }}/support_test.c" -o "{{ temp_compile.path }}/support_test"

  - name: Run support_test
    command: "{{ temp_compile.path }}/support_test"
    ignore_errors: yes
    register: support_test

  - name: Remove temp directory
    file:
      path: "{{ temp_compile.path }}"
      state: absent

  - name: Install kernel if needed
    include_tasks: install_kernel.yml
    when: support_test.rc != 0
  tags:
    - hardware_check
