- name: Clone repo
  git:
    repo: "{{ repo.libxdc.url }}"
    dest: "{{ repo.libxdc.root }}"
    version: "{{ repo.libxdc.revision | default(omit) }}"

- name: Build libxdc
  make:
    chdir: "{{ repo.libxdc.root }}"
    params:
      --jobs: "{{ ansible_processor_nproc }}"
  environment:
    C_INCLUDE_PATH: "{{ repo.capstone.root }}/include:{{ repo.libxdc.root }}"
    LIBRARY_PATH: "{{ repo.capstone.root }}:{{ repo.libxdc.root }}/"
    LD_LIBRARY_PATH: "{{ repo.capstone.root }}:{{ repo.libxdc.root }}/"
