- name: Configure QEMU
  command:
    argv:
      - ./configure
      - --target-list=x86_64-softmmu
      - --disable-gtk
      - --disable-docs
      - --disable-werror
      - --disable-capstone
      - --disable-libssh
      - --enable-virtfs
      - --enable-nyx
      - --enable-nyx-static
      - --disable-tools
    chdir: "{{ qemu_root }}"
  # TODO: duplicated env
  environment:
    C_INCLUDE_PATH: "{{ capstone_root }}/include:{{ libxdc_root }}"
    LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"
    LD_LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"

- name: Build QEMU
  make:
    chdir: "{{ qemu_root }}"
    params:
      NUM_THREADS: "{{ ansible_processor_nproc }}"
  environment:
    C_INCLUDE_PATH: "{{ capstone_root }}/include:{{ libxdc_root }}"
    LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"
    LD_LIBRARY_PATH: "{{ capstone_root }}:{{ libxdc_root }}/"