- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  with_items:
    - git
    - pkg-config
    - build-essential
    - libglib2.0-dev
    - libpixman-1-dev
    - libgtk-3-dev

- name: Install build dependencies for virtfs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - libcap-dev
    - libattr1-dev

- name: Configure Git User
  vars:
    github_user: "{{ lookup('env', 'GITHUB_USER') }}" 
    github_email: "{{ lookup('env', 'GITHUB_EMAIL') }}"
    deploy_key: "{{ lookup('env', 'GH_ACTION_DEPLOY_KEY') }}"
  ansible.builtin.shell: |
    git config --global user.name "{{github_user}}"
    git config --global user.email "{{github_email}}"
    mkdir -p ~/.ssh/
    echo "{{deploy_key}}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan github.com >> ~/.ssh/known_hosts


- name: Clone repo
  ansible.builtin.git:
    repo: "{{ qemu_url }}"
    dest: "{{ qemu_root }}"
    version: "{{ qemu_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
    recursive: false
    accept_hostkey: true
  tags:
    - clone

- name: Build QEMU
  ansible.builtin.command: ./compile_qemu_nyx.sh {{ qemu_build_type }}
  args:
    chdir: "{{ qemu_root }}"
  environment:
    CAPSTONE_ROOT: "{{ capstone_root }}"
    LIBXDC_ROOT: "{{ libxdc_root }}"
  when: not ansible_check_mode
  tags:
    - build
