- name: Import pre_tasks
  import_tasks: pre_tasks.yml

- name: Ensure kAFL parent directory exists
  file:
    path: "{{ install_root | dirname }}"
    state: directory

- name: Install kAFL system dependencies
  package:
    name: "{{ item }}"
  become: yes
  with_items:
    - libgraphviz-dev
    - python3-dev

- name: Ensure virtualenv command is available (Ansible pip module requirement)
  package:
    name: virtualenv
    state: present
  become: yes

- name: Clone repo
  git:
    repo: "{{ kafl_url }}"
    dest: "{{ kafl_root }}"
    version: "{{ kafl_revision | default('master') }}"
    depth: "{{ git_clone_depth | default(omit) }}"

- name: Install kAFL fuzzer
  pip:
    name: "file://{{ kafl_root }}"
    editable: yes
    virtualenv: "{{ install_root }}/venv"

- name: Import post_tasks
  import_tasks: post_tasks.yml
