name: CI

on:
  push:
    branches:
      - workspace
  pull_request:
    branches:
      - workspace

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2


      - name: Setup ansible
        run: |
          apt update && apt install -y make python3-venv
          make venv
          venv/bin/ansible-galaxy install -r requirements.yml

      # skip tags related to non-existent hardware/configuration in the CI runner environment
      - name: Test userspace deployment
        run: >
            venv/bin/ansible-playbook
            --inventory 'localhost,'
            --connection local
            site.yml
            --skip-tags "hardware_check,kvm_device"
