name: CI

on:
  push:
    branches:
      - workspace
  pull_request:
    branches:
      - workspace

jobs:
  deploy:
    runs-on: ubuntu-20.04

    container:
      image: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2

      - name: Test userspace deployment
        run: |
          apt update && apt install -y make python3-venv
          make venv
          venv/bin/ansible-playbook -i 'localhost,' -c local site.yml --extra-vars 'ignore_intel_pt_check=yes'
