name: CI

on:
  push:
    branches:
      - workspace
  pull_request:
    branches:
      - workspace

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Setup ansible
        run: |
          make venv

      # shallow clone for CI speed
      - name: Setup ansible extra vars in JSON file
        run: |
          echo '{"git_clone_depth": 1}' >> parameters.json

      # skip tags related to non-existent hardware/configuration in the CI runner environment
      - name: Test userspace deployment
        run: > 
          make deploy_local --
          --skip-tags "hardware_check,kvm_device"
          --extra-vars "@parameters.json"
